### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Justin652333** [The-Pixel-Project/maintainership#1]
---
name: Official maintainer form for The Pixel Project
about: Application for becoming an official maintainer for The Pixel Project
title: New maintainer 
assignees: Justin652333, hipexscape
---

## Name and Codename of the device you want to apply for 
...
Poco X3 Pro (Vayu)
...

## Device Tree sources

```
https://github.com/Justin652333/aosp_device_xiaomi_vayu.git    branch "fourteen"
https://github.com/GXC2356/platform_kernel_xiaomi_vayu.git    branch "main"
https://github.com/Justin652333/vendor_xiaomi_vayu.git           branch "fourteen"
```
### Have you gone through the maintainers requirements?
```
Yes
```

### How long have you been building Custom ROMs?
```
More than a month and a half 
```

### What ROM's do you maintain officially/unofficially?
```
Droidx (Unofficial)
EverestOs (Unofficial)
The Pixel Project (Unofficial)
```

### List of changes/patches applied to source, if applicable
```
Add here
```

### Telegram username

```
https://t.me/Justin_117
```
### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-oss-unofficial-the-pixel-project-v14-14-0-qpr3.4679714/
```
### Link to your unofficial The Pixel Project Build Post other than XDA

```
https://t.me/Justin117updates/56
```

**Comment by hipexscape** [comment]
Hey there,

After proper review, we couldn't find any significant contributions you made to the device which ensures whether you can fix any potential issues that arise.
We couldn't see much of what we would consider a reasonable knowledge after going through the changes you've done.

Try applying later again.

Your regards,
The Pixel Project Team
