### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by karthick-kk** [The-Pixel-Project/maintainership#3]
---
name: Official maintainer form for The Pixel Project
about: Application for becoming an official maintainer for The Pixel Project
title: New maintainer 
assignees: [separate the usernames with a comma]
---

## Name and Codename of the device you want to apply for 
```
Xiaomi 11T Pro 5G (vili)
```

## Device Tree sources

```
https://github.com/vili-develop/android_device_xiaomi_sm8350-common
https://github.com/vili-develop/android_device_xiaomi_vili
https://github.com/vili-develop/proprietary_vendor_xiaomi_sm8350-common
https://github.com/vili-develop/proprietary_vendor_xiaomi_vili
https://github.com/vili-develop/loskernel-devel

Source credit: (https://github.com/0mar99)
```
### Have you gone through the maintainers requirements?
```
Yes
```

### How long have you been building Custom ROMs?
```
an year
```

### What ROM's do you maintain officially/unofficially?
```
unofficial lineage, pixelos
```

### List of changes/patches applied to source, if applicable
```
https://github.com/crdroidandroid/android_device_xiaomi_sm8350-common/commit/0bd5334b4e807e845a6a3b27fd5b21b44f1d032f
```

### Telegram username

```
[KK](https://t.me/kknixx)
```
### Link to your XDA thread of unofficial build

```
NA
```

### Link to your unofficial The Pixel Project Build Post other than XDA

```
[Link to the public build post.](https://sourceforge.net/projects/kknixx-extended-roms/files/vili/PixelProject/)
```

**Comment by hipexscape** [comment]
Hey there karthick-kk,

After proper review, we couldn't find any significant contributions you made to the device which ensures whether you can fix any potential issues that arise.
We couldn't see much of what we would consider a reasonable knowledge after going through the changes you've done.

Try applying later again.

Your regards,
The Pixel Project Team
