### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by prique** [The-Pixel-Project/maintainership#4]
---
name: Official maintainer form for The Pixel Project
about: Application for becoming an official maintainer for The Pixel Project
title: New maintainer 
assignees: [separate the usernames with a comma]
---

## Name and Codename of the device you want to apply for 
```
Redmi Note 13 Pro 5G (Garnet)
```

## Device Tree sources

```
https://github.com/prique
```
### Have you gone through the maintainers requirements?
```
Yes
```

### How long have you been building Custom ROMs?
```
Some years
```

### What ROM's do you maintain officially/unofficially?
```
Project Blaze
```

### List of changes/patches applied to source, if applicable
```

```

### Telegram username

```
@PriQue77
```
### Link to your XDA thread of unofficial build

```
At the moment I only made private builds
```

### Link to your unofficial The Pixel Project Build Post other than XDA

```
At the moment I only made private builds
```

**Comment by username0136** [comment]
Do publish some builds publicly, and reapply after a month.

**Comment by prique** [comment]
> Do publish some builds publicly, and reapply after a month.

Understood. So I can solve the certification I will share the first build!!  :)
