### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by username0136** [The-Pixel-Project/maintainership#5]
## Name and Codename of the device you want to apply for 
```
POCO F4 / Redmi K40S (munch)
```

## Device Tree sources

```
https://github.com/username0136/device_xiaomi_sm8250-common
https://github.com/username0136/device_xiaomi_munch
https://github.com/kvsnr113/xiaomi_sm8250_kernel
https://gitlab.com/munch-qwik/vt/1_vendor_xiaomi_sm8250-common
https://gitlab.com/munch-qwik/vt/1_vendor_xiaomi_munch
```

### Have you gone through the maintainers requirements?
```
Yes
```

### How long have you been building Custom ROMs?
```
10 months to 1 year approx.
I don't remember exactly
```

### What ROM's do you maintain officially/unofficially?
```
PixelOS unofficial with tweaked source and OTA support
```

### Telegram username

```
https://t.me/username0138
```

### Link to your XDA thread of unofficial build

```
I don't use XDA, if there's a requirement to get it posted on XDA, I'll post it
```

### Link to your unofficial The Pixel Project Build Post other than XDA

```
I already built official for munch device and will be soon released on F4 channel (core member: mudit allowed me)
He asked to get this form filled for logging purposes
```

**Comment by JoeChirico** [comment]
Hey there Quick ⚡,

After a thorough review, we found that you have made significant contributions to the device, demonstrating your ability to address any potential issues that may arise. We were impressed by the depth of your knowledge and the quality of the changes you've implemented.

We are excited to move forward with your application and will contact you soon with further details regarding the next steps.

Your regards,
The Pixel Project Team
