### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by tanvirr007** [The-Pixel-Project/maintainership#6]
---
name: Official maintainer form for The Pixel Project
about: Application for becoming an official maintainer for The Pixel Project
title: New maintainer 
assignees: @JoeChirico 
---

## Name and Codename of the device you want to apply for 
```
Redmi Note 11 (spes/spesn)
```

## Device Tree sources

```
https://github.com/tanvirr007/device_xiaomi_spes
https://github.com/tanvirr007/kernel_xiaomi_sm6225/tree/NaughtySilver
https://github.com/tanvirr007/vendor_xiaomi_spes
```
### Have you gone through the maintainers requirements?
```
Yes
```

### How long have you been building Custom ROMs?
```
Almost 1 year
```

### What ROM's do you maintain officially/unofficially?
```
AfterLife Project (unofficially)
FireDroid (unofficially)
AwakenOS (unofficially)
FireDroid and AfterLife seems dead. Now I'm willing to stick with The Pixel Project.
```

### List of changes/patches applied to source, if applicable
```
https://github.com/tanvirr007/device_xiaomi_spes/commit/1aa4f43dbd038566601622ba5007d7bafb0f449b
```

### Telegram username

```
https://t.me/tanvirr007
```
### Link to your XDA thread of unofficial build

```
N/A
```

### Link to your unofficial The Pixel Project Build Post other than XDA

```
https://t.me/RedmiNote11_Updates/518
```

**Comment by hipexscape** [comment]
Hi here tanvirr007,

We were just going though your trees and found that  your tree meets our standards and you will be accepted as maintainer after you fix commits like 

https://github.com/tanvirr007/device_xiaomi_spes/commit/0c573d13a225ad1bb5ac7b5fb2607448817dad1b

I would like you to rebased these type of commits

Regards,
The Pixel Project Team

**Comment by sajidshahriar72543** [comment]
Hello @tanvirr007,

While checking the trees mentioned in the application, few issues I've pointed out (mostly minor). For your convenience, I'll enlist those here. 

https://github.com/tanvirr007/device_xiaomi_spes/commit/2a593c785360094a8a3a4f75e46e8befc42b62cd
TEMPORARY right? Please remove this ASAP.

https://github.com/tanvirr007/device_xiaomi_spes/commit/351ad77b9fd94183439918045f4cfa373a46d5c2#diff-fe6362b843db7ac7e179ab17ee576e49cde1ccda60fbcb48c2f15054ca5d372aR2
You SHOULD NOT change the copyrights.

https://github.com/tanvirr007/device_xiaomi_spes/commit/351ad77b9fd94183439918045f4cfa373a46d5c2#diff-c8d4b4624e7a1b2422b7280a6ecb2ba76d7bed01a82c3d28937b745627ab2557R35-R41
You are sure these flags are present in the source?

https://github.com/tanvirr007/kernel_xiaomi_sm6225/commit/6f4fcdfb33d0a63fb00b600a11d16fdb2473e358
Seems like you've messed up the authorship here. Give it a recheck maybe?

Please revise the issues and update us as soon as possible.

Regards,
sajidshahriar72543
On behalf of **The Pixel Project Team**.

**Comment by tanvirr007** [comment]
Hi @JoeChirico , @sajidshahriar72543
I have addressed all the issues mentioned:
• Rebased the necessary commits.
• Removed the temporary changes.
• Restored the original copyrights.
• Verified the flags in the source.
• Corrected the authorship in the kernel repository.

Please review the updated repositories,and let me know if any more updates needs to be done.

Best regards,
@tanvirr007

**Comment by hipexscape** [comment]
Hey @tanvirr007,

Please message me on telegram
https://t.me/hipexscape
