### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AgBKartikey** [The-Pixel-Project/maintainership#7]
---
name: Official maintainer form for The Pixel Project
about: Application for becoming an official maintainer for The Pixel Project
title: New maintainer 
assignees: AgBKartikey
---

## Name and Codename of the device you want to apply for 
```
Nothing Phone 2 (Pong)
```

## Device Tree sources
```
https://github.com/AgBKartikey/device-nothing-Pong/tree/pixelproject
https://github.com/HELLBOY017/kernel_nothing_sm8475/tree/inline
https://github.com/AgBKartikey/vendor-nothing-Pong/tree/udc-BI
```
### Have you gone through the maintainers requirements?
```
Yes
```

### How long have you been building Custom ROMs?
```
1 Month
```

### What ROM's do you maintain officially/unofficially?
```
StagOS (Official)
LMODroid, BlackIron (Unofficial)
```

### List of changes/patches applied to source, if applicable
```
Sepolicy
Display-Hal
```

### Telegram username
```
https://t.me/AgBKartikey
```
### Link to your XDA thread of unofficial build
```
NA
```

### Link to your unofficial The Pixel Project Build Post other than XDA
```
https://t.me/NothingPhone2/400564
```

**Comment by sajidshahriar72543** [comment]
Hello @AgBKartikey 

Upon checking your device resources included in the application, I'm sorry that you don't satisfy the regulations for being accepted as an official maintainer. Hence, I'm closing the issue.

What went wrong:
- The device tree commits history (commits done by you) is awful.

What to fix:
- Learn git properly
- Gain some more experience in rom building field
- Release an unofficial build
- Go through the maintainer's requirements AGAIN.

Regards,
@sajidshahriar72543 
On behalf of **The Pixel Project** team.
